# Generated by Django 3.1.1 on 2020-09-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
