# Generated by Django 3.1.1 on 2020-09-19 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0007_remove_like_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reqed', to=settings.AUTH_USER_MODEL)),
                ('user_requesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reqing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpage.chatroom')),
            ],
        ),
    ]
