# Generated by Django 3.1.1 on 2020-09-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0011_chat_chatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chatter1',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
