# Generated by Django 3.1.1 on 2020-09-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0013_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='nestedcommentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested', to=settings.AUTH_USER_MODEL),
        ),
    ]
