# Generated by Django 3.1.1 on 2020-09-23 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0017_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='followed',
            field=models.ManyToManyField(related_name='followinguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
